<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>DataScorpio.EntityFrameworkCore</PackageId>
    <Description>Entity Framework Core execution adapter for DataScorpio.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    <ProjectReference Include="..\DataScorpio\DataScorpio.csproj" />
  </ItemGroup>
</Project>
